import type { ProductRecord } from "@/types/product";

/**
 * Sample product records kept as a local dev/design fixture — no longer
 * read by the live dashboard (see hooks/use-dashboard-data.ts, which now
 * calls the real /api/products route backed by Google Sheets, Milestone 8).
 * Still useful for working on dashboard/table UI without Sheets configured.
 * Shapes and field names mirror `ProductRecord` exactly.
 */
export const MOCK_PRODUCTS: ProductRecord[] = [
  {
    productId: "SP-1042",
    category: "earrings",
    title: "Golden Bloom Hoops",
    description: "Hammered gold hoops with a soft floral curve.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 4.8,
    lengthCm: 3.2,
    widthCm: 2.1,
    finish: "Polished Gold",
    stone: "None",
    hookType: "Lever Back",
    ringSize: null,
    bandWidthMm: null,
    claspType: null,
    chainIncluded: null,
    collections: ["Bestsellers", "Hoops"],
    inventory: 18,
    status: "published",
    driveFolder: "SELEN Products/Earrings/Golden Bloom Hoops",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-07-29",
    shopifyProductId: "gid://shopify/Product/8817231",
  },
  {
    productId: "SP-1041",
    category: "ring",
    title: "Luna Twist Ring",
    description: "A twisting band that catches light from every angle.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 3.1,
    lengthCm: null,
    widthCm: null,
    finish: "Brushed Silver",
    stone: "Moonstone",
    hookType: null,
    ringSize: "7",
    bandWidthMm: 2.4,
    claspType: null,
    chainIncluded: null,
    collections: ["New Arrivals"],
    inventory: 24,
    status: "published",
    driveFolder: "SELEN Products/Ring/Luna Twist Ring",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-07-28",
    shopifyProductId: "gid://shopify/Product/8817180",
  },
  {
    productId: "SP-1040",
    category: "pendant",
    title: "Ocean Pearl Drop",
    description: "A single freshwater pearl suspended on a fine chain.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 2.4,
    lengthCm: 1.8,
    widthCm: 1.1,
    finish: "Polished Gold",
    stone: "Pearl",
    hookType: null,
    ringSize: null,
    bandWidthMm: null,
    claspType: null,
    chainIncluded: true,
    collections: ["Bestsellers"],
    inventory: 12,
    status: "published",
    driveFolder: "SELEN Products/Pendant/Ocean Pearl Drop",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-07-26",
    shopifyProductId: "gid://shopify/Product/8817012",
  },
  {
    productId: "SP-1039",
    category: "necklace",
    title: "Amber Cascade",
    description: "Layered amber-toned stones on a delicate chain.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 6.2,
    lengthCm: 42,
    widthCm: null,
    finish: "Matte Gold",
    stone: "Citrine",
    hookType: null,
    ringSize: null,
    bandWidthMm: null,
    claspType: "Lobster Clasp",
    chainIncluded: null,
    collections: ["Statement"],
    inventory: 0,
    status: "processing",
    driveFolder: "SELEN Products/Necklace/Amber Cascade",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-08-03",
    shopifyProductId: null,
  },
  {
    productId: "SP-1038",
    category: "bracelet",
    title: "Woven Dune Cuff",
    description: "An open cuff with a woven, sand-textured finish.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 9.4,
    lengthCm: 17,
    widthCm: 1.4,
    finish: "Brushed Gold",
    stone: "None",
    hookType: null,
    ringSize: null,
    bandWidthMm: null,
    claspType: "Toggle Clasp",
    chainIncluded: null,
    collections: [],
    inventory: 0,
    status: "processing",
    driveFolder: "SELEN Products/Bracelet/Woven Dune Cuff",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-08-03",
    shopifyProductId: null,
  },
  {
    productId: "SP-1037",
    category: "earrings",
    title: "Ember Drop Studs",
    description: "Petite garnet studs with a warm ember glow.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 2.1,
    lengthCm: 1.2,
    widthCm: 0.6,
    finish: "Polished Gold",
    stone: "Garnet",
    hookType: "Push Back",
    ringSize: null,
    bandWidthMm: null,
    claspType: null,
    chainIncluded: null,
    collections: ["New Arrivals"],
    inventory: 0,
    status: "failed",
    driveFolder: "SELEN Products/Earrings/Ember Drop Studs",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-08-02",
    shopifyProductId: null,
  },
  {
    productId: "SP-1036",
    category: "ring",
    title: "Ivy Vine Band",
    description: "A slender band etched with a trailing vine motif.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 2.8,
    lengthCm: null,
    widthCm: null,
    finish: "Polished Gold",
    stone: "None",
    hookType: null,
    ringSize: "6.5",
    bandWidthMm: 1.8,
    claspType: null,
    chainIncluded: null,
    collections: [],
    inventory: 0,
    status: "draft",
    driveFolder: "SELEN Products/Ring/Ivy Vine Band",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-08-01",
    shopifyProductId: null,
  },
  {
    productId: "SP-1035",
    category: "pendant",
    title: "Solstice Sunburst",
    description: "A radiant sunburst pendant in warm rose gold.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 3.6,
    lengthCm: 2.2,
    widthCm: 2.2,
    finish: "Rose Gold",
    stone: "None",
    hookType: null,
    ringSize: null,
    bandWidthMm: null,
    claspType: null,
    chainIncluded: false,
    collections: ["Statement"],
    inventory: 0,
    status: "draft",
    driveFolder: "SELEN Products/Pendant/Solstice Sunburst",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-07-31",
    shopifyProductId: null,
  },
  {
    productId: "SP-1034",
    category: "necklace",
    title: "Silver Horizon Chain",
    description: "A minimal, everyday chain with a satin finish.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 5.5,
    lengthCm: 45,
    widthCm: null,
    finish: "Brushed Silver",
    stone: "None",
    hookType: null,
    ringSize: null,
    bandWidthMm: null,
    claspType: "Spring Ring",
    chainIncluded: null,
    collections: ["Bestsellers", "Everyday"],
    inventory: 30,
    status: "published",
    driveFolder: "SELEN Products/Necklace/Silver Horizon Chain",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-07-24",
    shopifyProductId: "gid://shopify/Product/8816810",
  },
  {
    productId: "SP-1033",
    category: "bracelet",
    title: "Pearl Chain Link",
    description: "Freshwater pearls set between polished gold links.",
    tags: [],
    seoTitle: "",
    metaDescription: "",
    weightGrams: 7.1,
    lengthCm: 18,
    widthCm: 0.8,
    finish: "Polished Gold",
    stone: "Pearl",
    hookType: null,
    ringSize: null,
    bandWidthMm: null,
    claspType: "Lobster Clasp",
    chainIncluded: null,
    collections: ["Bestsellers"],
    inventory: 9,
    status: "published",
    driveFolder: "SELEN Products/Bracelet/Pearl Chain Link",
    heroImageLink: "",
    lifestyleImageLink: "",
    closeupImageLink: "",
    createdDate: "2026-07-20",
    shopifyProductId: "gid://shopify/Product/8816502",
  },
];
